/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test2.check" instead.
 */

#include <check.h>

#line 1 "test2.check"
#include <string.h>

#include "s21_string.h"

START_TEST(sprintf_test_c) {
#line 6
  char array1[100];
  char array2[100];
  char test1 = 50;
  char test2 = 55;
  s21_sprintf(array1, "%c", test1);
  sprintf(array2, "%c", test1);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%10c", test2);
  sprintf(array2, "%10c", test2);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%-20c", test2);
  sprintf(array2, "%-20c", test2);
  ck_assert_str_eq(array1, array2);
}
END_TEST

START_TEST(sprintf_test_d) {
#line 21
  char array1[100];
  char array2[100];
  short test1 = 20;
  int test2 = 12456;
  long test3 = 543256789;
  s21_sprintf(array1, "%- .5hd", test1);
  sprintf(array2, "%- .5hd", test1);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%5d", test2);
  sprintf(array2, "%5d", test2);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%+5d", test2);
  sprintf(array2, "%+5d", test2);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%-+10ld", test3);
  sprintf(array2, "%-+10ld", test3);
  ck_assert_str_eq(array1, array2);
}
END_TEST

START_TEST(sprintf_test_f) {
#line 40
  char array1[100];
  char array2[100];
  float test1 = 21.21;
  double test2 = 21.322;
  long double test3 = 21.2121212121;
  double test4 = INFINITY;
  double test5 = NAN;
  s21_sprintf(array1, "%- .15f", test1);
  sprintf(array2, "%- .15f", test1);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%-+15lf", test2);
  sprintf(array2, "%-+15lf", test2);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%-+15.Lf", test3);
  sprintf(array2, "%-+15.Lf", test3);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%+15lf", test2);
  sprintf(array2, "%+15lf", test2);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%lf", test4);
  sprintf(array2, "%lf", test4);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%lf", test5);
  sprintf(array2, "%lf", test5);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%f", test1);
  sprintf(array2, "%f", test1);
  ck_assert_str_eq(array1, array2);
}
END_TEST

START_TEST(sprintf_test_s) {
#line 70
  char array1[100];
  char array2[100];
  char *test1 = "School 21";
  s21_sprintf(array1, "%s", test1);
  sprintf(array2, "%s", test1);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%20s", test1);
  sprintf(array2, "%20s", test1);
  ck_assert_str_eq(array1, array2);
}
END_TEST

START_TEST(sprintf_test_u) {
#line 81
  char array1[100];
  char array2[100];
  unsigned short test1 = -20;
  unsigned int test2 = -1;
  unsigned long test3 = -5;
  s21_sprintf(array1, "%-.5hu", test1);
  sprintf(array2, "%-.5hu", test1);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%5u", test2);
  sprintf(array2, "%5u", test2);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%5u", test2);
  sprintf(array2, "%5u", test2);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%-10lu", test3);
  sprintf(array2, "%-10lu", test3);
  ck_assert_str_eq(array1, array2);
}
END_TEST

START_TEST(sprintf_test_percent) {
#line 100
  char array1[100];
  char array2[100];
  int test1 = 21;
  double test2 = 21.2121;
  s21_sprintf(array1, "%% kek %d", test1);
  sprintf(array2, "%% kek %d", test1);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%% kek %lf", test2);
  sprintf(array2, "%% kek %lf", test2);
  ck_assert_str_eq(array1, array2);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, sprintf_test_c);
  tcase_add_test(tc1_1, sprintf_test_d);
  tcase_add_test(tc1_1, sprintf_test_f);
  tcase_add_test(tc1_1, sprintf_test_s);
  tcase_add_test(tc1_1, sprintf_test_u);
  tcase_add_test(tc1_1, sprintf_test_percent);
  srunner_set_fork_status(sr, CK_NOFORK);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
