/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test5.check" instead.
 */

#include <check.h>

#line 1 "test5.check"

#include "s21_string.h"

START_TEST(csharp_to_upper) {
#line 5
  char *test = "SCHool 21";
  char *compare = "SCHOOL 21";
  char *res = s21_to_upper(test);
  ck_assert_str_eq(res, compare);
  free(res);
}
END_TEST

START_TEST(csharp_to_lower) {
#line 12
  char *test = "SCHOOL 21";
  char *compare = "school 21";
  char *res = s21_to_lower(test);
  ck_assert_str_eq(res, compare);
  free(res);
}
END_TEST

START_TEST(csharp_insert) {
#line 19
  char *test1 = "School";
  char *test2 = " 21";
  char *compare1 = "School 21";
  char *compare2 = "Scho 21ol";
  char *res = s21_NULL;
  res = s21_insert(test1, test2, 6);
  ck_assert_str_eq(res, compare1);
  free(res);
  res = s21_insert(test1, test2, 4);
  ck_assert_str_eq(res, compare2);
  free(res);
}
END_TEST

START_TEST(csharp_trim) {
#line 32
  char *test1 = " \n\b School 21 \n\b";
  char *trm1 = " \n\b";
  char *compare = "School 21";
  char *res = s21_NULL;
  res = s21_trim(test1, trm1);
  ck_assert_str_eq(res, compare);
  free(res);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, csharp_to_upper);
  tcase_add_test(tc1_1, csharp_to_lower);
  tcase_add_test(tc1_1, csharp_insert);
  tcase_add_test(tc1_1, csharp_trim);
  srunner_set_fork_status(sr, CK_NOFORK);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
