/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test4.check" instead.
 */

#include <check.h>

#line 1 "test4.check"
#include "s21_string.h"

START_TEST(sscanf_test_c) {
#line 4
  char *buf = "school21";
  char first;
  char second;
  char first_1;
  char second_1;
  s21_sscanf(buf, "%c%*c%c", &first, &second);
  sscanf(buf, "%c%*c%c", &first_1, &second_1);
  ck_assert_int_eq(first, first_1);
  ck_assert_int_eq(second, second_1);
}
END_TEST

START_TEST(sscanf_test_d) {
#line 15
  char *buf = "32221 % -155";
  int first;
  short second;
  long third;
  int first_1;
  short second_1;
  long third_1;
  s21_sscanf(buf, "%3d%hd%%%ld", &first, &second, &third);
  sscanf(buf, "%3d%hd%%%ld", &first_1, &second_1, &third_1);
  ck_assert_int_eq(first, first_1);
  ck_assert_int_eq(second, second_1);
  ck_assert_int_eq(third, third_1);
}
END_TEST

START_TEST(sscanf_test_f) {
#line 29
  char *buf = "321.212121 21e+02 21e+12";
  float first;
  double second;
  long double third;
  float first_1;
  double second_1;
  long double third_1;
  s21_sscanf(buf, "%5f%lg%Le", &first, &second, &third);
  sscanf(buf, "%5f%lg%Le", &first_1, &second_1, &third_1);
  ck_assert_float_eq(first, first_1);
  ck_assert_double_eq(second, second_1);
  ck_assert_ldouble_eq(third, third_1);
}
END_TEST

START_TEST(sscanf_test_f_inf) {
#line 43
  char *buf = "INFINITY -inf NAN";
  double first, second, third;
  double first_1, second_1, third_1;
  s21_sscanf(buf, "%lf%lf%lf", &first, &second, &third);
  sscanf(buf, "%lf%lf%lf", &first_1, &second_1, &third_1);
  ck_assert_double_eq(first, first_1);
  ck_assert_double_eq(second, second_1);
  ck_assert_double_ne(third, third_1);
}
END_TEST

START_TEST(sscanf_test_s) {
#line 53
  char *buf = "School 21 is cool";
  char array1[100];
  char array2[100];
  s21_sscanf(buf, "%s", array1);
  sscanf(buf, "%s", array2);
  ck_assert_str_eq(array1, array2);
  s21_sscanf(buf, "%5s", array1);
  sscanf(buf, "%5s", array2);
  ck_assert_str_eq(array1, array2);
}
END_TEST

START_TEST(sscanf_test_u) {
#line 64
  char *buf = "32221 -155";
  unsigned int first;
  unsigned short second;
  unsigned long third;
  unsigned int first_1;
  unsigned short second_1;
  unsigned long third_1;
  s21_sscanf(buf, "%3u%hu%lu", &first, &second, &third);
  sscanf(buf, "%3u%hu%lu", &first_1, &second_1, &third_1);
  ck_assert_uint_eq(first, first_1);
  ck_assert_uint_eq(second, second_1);
  ck_assert_uint_eq(third, third_1);
}
END_TEST

START_TEST(sscanf_test_x) {
#line 78
  char *buf = "32221 0xFFF";
  unsigned int first;
  unsigned short second;
  unsigned long third;
  unsigned int first_1;
  unsigned short second_1;
  unsigned long third_1;
  s21_sscanf(buf, "%3x%hx%lx", &first, &second, &third);
  sscanf(buf, "%3x%hx%lx", &first_1, &second_1, &third_1);
  ck_assert_uint_eq(first, first_1);
  ck_assert_uint_eq(second, second_1);
  ck_assert_uint_eq(third, third_1);
}
END_TEST

START_TEST(sscanf_test_o) {
#line 92
  char *buf = "32221 -155";
  unsigned int first;
  unsigned short second;
  unsigned long third;
  unsigned int first_1;
  unsigned short second_1;
  unsigned long third_1;
  s21_sscanf(buf, "%3o%ho%lo", &first, &second, &third);
  sscanf(buf, "%3o%ho%lo", &first_1, &second_1, &third_1);
  ck_assert_uint_eq(first, first_1);
  ck_assert_uint_eq(second, second_1);
  ck_assert_uint_eq(third, third_1);
}
END_TEST

START_TEST(sscanf_test_p) {
#line 106
  char *buf = "4124124 23213 322";
  char array1[100];
  char array2[100];
  unsigned int *first;
  unsigned int *second;
  unsigned int *third;
  unsigned int *first_1;
  unsigned int *second_1;
  unsigned int *third_1;
  s21_sscanf(buf, "%p%p%p", &first, &second, &third);
  sscanf(buf, "%p%p%p", &first_1, &second_1, &third_1);
  s21_sprintf(array1, "%p", first);
  s21_sprintf(array2, "%p", first_1);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%p", second);
  s21_sprintf(array2, "%p", second_1);
  ck_assert_str_eq(array1, array2);
  s21_sprintf(array1, "%p", third);
  s21_sprintf(array2, "%p", third_1);
  ck_assert_str_eq(array1, array2);
}
END_TEST

START_TEST(sscanf_test_ni) {
#line 128
  char *buf = "0123 0xFAA 322";
  unsigned int first, second, third, first_1, second_1, third_1;
  int n, n_1;
  s21_sscanf(buf, "%i%n%i%i", &first, &n, &second, &third);
  sscanf(buf, "%i%n%i%i", &first_1, &n_1, &second_1, &third_1);
  ck_assert_uint_eq(first, first_1);
  ck_assert_uint_eq(second, second_1);
  ck_assert_uint_eq(third, third_1);
  ck_assert_int_eq(n, n_1);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;
  srunner_set_fork_status(sr, CK_NOFORK);

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, sscanf_test_c);
  tcase_add_test(tc1_1, sscanf_test_d);
  tcase_add_test(tc1_1, sscanf_test_f);
  tcase_add_test(tc1_1, sscanf_test_f_inf);
  tcase_add_test(tc1_1, sscanf_test_s);
  tcase_add_test(tc1_1, sscanf_test_u);
  tcase_add_test(tc1_1, sscanf_test_x);
  tcase_add_test(tc1_1, sscanf_test_o);
  tcase_add_test(tc1_1, sscanf_test_p);
  tcase_add_test(tc1_1, sscanf_test_ni);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
