/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source
 * file "file.check" instead.
 */

#include <check.h>

#line 1 "file.check"
#include <check.h>

#include "s21_tetris.h"

START_TEST(init_object_test) {
#line 5
  main_game();
  GameInfo_t var;
  FILE *file = fopen("brick_game/tetris/high_score.txt", "r+");
  ck_assert_int_eq(init_object(&var, file), 0);
  free_field(&var);
  free_next(&var);
  ck_assert_int_eq(init_object(NULL, NULL), 1);
  fclose(file);
}
END_TEST

START_TEST(memory_alloc_test) {
#line 15
  GameInfo_t var;
  ck_assert_int_eq(memory_allocation_field(&var), 0);
  free_field(&var);
  ck_assert_int_eq(memory_allocation_field(NULL), 1);
}
END_TEST

START_TEST(read_high_score_test) {
#line 21
  int ptr = 1000;
  FILE *file = fopen("brick_game/tetris/high_score.txt", "r+");
  ck_assert_int_eq(read_high_score(&ptr, file), 0);
  ck_assert_int_eq(200, ptr);
  ck_assert_int_eq(read_high_score(NULL, file), 1);
  ck_assert_int_eq(read_high_score(NULL, NULL), 1);
  fclose(file);
}
END_TEST

START_TEST(init_ints_test) {
#line 30
  GameInfo_t var;
  ck_assert_int_eq(init_ints(&var), 0);
  ck_assert_int_eq(init_ints(NULL), 1);
}
END_TEST

START_TEST(memory_allocation_next_test) {
#line 35
  GameInfo_t var;
  ck_assert_int_eq(memory_allocation_next(&var), 0);
  free_next(&var);
  ck_assert_int_eq(memory_allocation_next(NULL), 1);
}
END_TEST

START_TEST(init_next_figure_test) {
#line 41
  GameInfo_t var;
  memory_allocation_next(&var);
  ck_assert_int_eq(init_next_figure(&var), 0);
  free_next(&var);
  ck_assert_int_eq(init_next_figure(NULL), 1);
}
END_TEST

START_TEST(init_current_figure_test) {
#line 48
  figure a;
  GameInfo_t var;
  memory_allocation_figure(&a);
  memory_allocation_next(&var);
  ck_assert_int_eq(init_current_figure(&a, var.next), 0);
  ck_assert_int_eq(init_current_figure(&a, NULL), 1);
  ck_assert_int_eq(init_current_figure(NULL, NULL), 1);
  free_figure(&a);
  free_next(&var);
}
END_TEST

START_TEST(moving_test) {
#line 60
  figure var;
  memory_allocation_figure(&var);
  var.x = 5;
  var.y = 1;
  ck_assert_int_eq(move_down(&var), 0);
  ck_assert_int_eq(move_up(&var), 0);
  ck_assert_int_eq(move_left(&var), 0);
  ck_assert_int_eq(move_right(&var), 0);
  ck_assert_int_eq(move_down(NULL), 1);
  ck_assert_int_eq(move_up(NULL), 1);
  ck_assert_int_eq(move_left(NULL), 1);
  ck_assert_int_eq(move_right(NULL), 1);
  ck_assert_int_eq(var.x, 5);
  ck_assert_int_eq(var.y, 1);
  free_figure(&var);
}
END_TEST

START_TEST(collision_test) {
#line 77
  GameInfo_t pole;
  figure figure;
  memory_allocation_field(&pole);
  memory_allocation_figure(&figure);
  ck_assert_int_eq(collision(pole, figure), 0);
  for (int i = 0; i < VALUE_SAMPLE; i++) {
    for (int j = 0; j < VALUE_SAMPLE; j++) {
      figure.blocks[i][j] = 1;
    }
  }
  for (int i = 0; i < HEIGHT_MAIN; i++) {
    for (int j = 0; j < WIDTH_MAIN; j++) {
      pole.field[i][j] = 1;
    }
  }
  ck_assert_int_eq(collision(pole, figure), 1);
  free_field(&pole);
  free_figure(&figure);
}
END_TEST

START_TEST(put_current_test) {
#line 101
  GameInfo_t pole;
  figure figure;
  memory_allocation_field(&pole);
  memory_allocation_figure(&figure);
  ck_assert_int_eq(put_current(&pole, figure), 0);
  ck_assert_int_eq(put_current(NULL, figure), 1);
  free_field(&pole);
  free_figure(&figure);
}
END_TEST

START_TEST(count_points_test) {
#line 111
  GameInfo_t pole;
  memory_allocation_field(&pole);
  init_field(&pole, 0);
  ck_assert_int_eq(count_points(&pole), 0);
  init_field(&pole, 1);
  ck_assert_int_eq(count_points(&pole), 1500);
  free_field(&pole);
}
END_TEST

START_TEST(filled_line_test) {
#line 120
  GameInfo_t pole;
  memory_allocation_field(&pole);
  init_field(&pole, 0);
  ck_assert_int_eq(filled_line(5, &pole), 0);
  init_field(&pole, 1);
  ck_assert_int_eq(filled_line(4, &pole), 1);
  free_field(&pole);
}
END_TEST

START_TEST(move_upper_lines_test) {
#line 129
  GameInfo_t pole;
  memory_allocation_field(&pole);
  init_field(&pole, 1);
  ck_assert_int_eq(move_upper_lines(12, &pole), 0);
  ck_assert_int_eq(move_upper_lines(13, NULL), 1);
  free_field(&pole);
}
END_TEST

START_TEST(update_score_test) {
#line 137
  GameInfo_t pole;
  memory_allocation_field(&pole);
  init_field(&pole, 1);
  ck_assert_int_eq(update_score(&pole), 0);
  ck_assert_int_eq(update_score(NULL), 1);
  free_field(&pole);
}
END_TEST

START_TEST(create_new_figure_test) {
#line 145
  GameInfo_t pole;
  figure current;
  memory_allocation_field(&pole);
  memory_allocation_next(&pole);
  memory_allocation_figure(&current);
  ck_assert_int_eq(create_new_figure(&pole, &current), 0);
  ck_assert_int_eq(create_new_figure(&pole, NULL), 1);
  ck_assert_int_eq(create_new_figure(NULL, NULL), 1);
  ck_assert_int_eq(create_new_figure(NULL, &current), 1);
  free_field(&pole);
  free_figure(&current);
  free_next(&pole);
}
END_TEST

START_TEST(free_figure_test) {
#line 159
  figure current;
  memory_allocation_figure(&current);
  free_figure(&current);
  free_figure(NULL);
}
END_TEST

START_TEST(memory_allocation_figure_test) {
#line 165
  figure current;
  ck_assert_int_eq(memory_allocation_figure(&current), 0);
  free_figure(&current);
  ck_assert_int_eq(memory_allocation_figure(NULL), 1);
}
END_TEST

START_TEST(erase_field_test) {
#line 171

  GameInfo_t pole;
  memory_allocation_field(&pole);
  figure current;
  memory_allocation_figure(&current);
  ck_assert_int_eq(erase_field(&pole, current), 0);
  ck_assert_int_eq(erase_field(NULL, current), 1);
  free_figure(&current);
  free_field(&pole);
}
END_TEST

START_TEST(free_in_the_end_of_game_test) {
#line 182
  GameInfo_t pole;
  figure current;
  memory_allocation_field(&pole);
  memory_allocation_next(&pole);
  memory_allocation_figure(&current);
  free_in_the_end_of_game(&pole, &current);
  free_in_the_end_of_game(NULL, NULL);
}
END_TEST

START_TEST(rotate_figure_test) {
#line 191
  GameInfo_t pole;
  figure current;
  memory_allocation_field(&pole);
  memory_allocation_figure(&current);
  ck_assert_int_eq(rotate_figure(&pole, &current), 0);
  ck_assert_int_eq(rotate_figure(NULL, NULL), 1);
  free_field(&pole);
  free_figure(&current);
}
END_TEST

START_TEST(clear_field_test) {
#line 201
  GameInfo_t pole;
  memory_allocation_field(&pole);
  ck_assert_int_eq(clear_field(&pole), 0);
  ck_assert_int_eq(clear_field(NULL), 1);
  free_field(&pole);
}
END_TEST

START_TEST(writening_high_score_test) {
#line 208
  int number = 200;
  ck_assert_int_eq(writening_high_score(number), 0);
}
END_TEST

START_TEST(square_test) {
#line 212

  figure current;
  memory_allocation_figure(&current);
  ck_assert_int_eq(square(&current), 0);
  ck_assert_int_eq(square(NULL), 1);
  free_figure(&current);
}
END_TEST

START_TEST(writening_current_test) {
#line 220
  GameInfo_t var;
  var = writening_current_figure(1, 1, 0, 0);
  ck_assert_int_eq(var.score, 0);
  ck_assert_int_eq(var.high_score, 200);
  ck_assert_int_eq(var.level, 0);
  ck_assert_int_eq(var.speed, 0);
  ck_assert_int_eq(var.pause, 0);
  writening_current_figure(0, 0, 0, Terminate);
}
END_TEST

START_TEST(action_pause_test) {
#line 230
  GameInfo_t var;
  var = writening_current_figure(1, 1, 0, Pause);
  ck_assert_int_eq(var.pause, 1);
  writening_current_figure(0, 0, 0, Terminate);
}
END_TEST

START_TEST(move_test) {
#line 236
  GameInfo_t var;
  figure current;
  memory_allocation_field(&var);
  memory_allocation_next(&var);
  memory_allocation_figure(&current);
  init_field(&var, 0);
  current.x = 3;
  do_action(&var, &current, Left, 200);
  ck_assert_int_eq(current.x, 2);
  do_action(&var, &current, Right, 200);
  ck_assert_int_eq(current.x, 3);
  free_field(&var);
  free_next(&var);
  free_figure(&current);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, init_object_test);
  tcase_add_test(tc1_1, memory_alloc_test);
  tcase_add_test(tc1_1, read_high_score_test);
  tcase_add_test(tc1_1, init_ints_test);
  tcase_add_test(tc1_1, memory_allocation_next_test);
  tcase_add_test(tc1_1, init_next_figure_test);
  tcase_add_test(tc1_1, init_current_figure_test);
  tcase_add_test(tc1_1, moving_test);
  tcase_add_test(tc1_1, collision_test);
  tcase_add_test(tc1_1, put_current_test);
  tcase_add_test(tc1_1, count_points_test);
  tcase_add_test(tc1_1, filled_line_test);
  tcase_add_test(tc1_1, move_upper_lines_test);
  tcase_add_test(tc1_1, update_score_test);
  tcase_add_test(tc1_1, create_new_figure_test);
  tcase_add_test(tc1_1, free_figure_test);
  tcase_add_test(tc1_1, memory_allocation_figure_test);
  tcase_add_test(tc1_1, erase_field_test);
  tcase_add_test(tc1_1, free_in_the_end_of_game_test);
  tcase_add_test(tc1_1, rotate_figure_test);
  tcase_add_test(tc1_1, clear_field_test);
  tcase_add_test(tc1_1, writening_high_score_test);
  tcase_add_test(tc1_1, square_test);
  tcase_add_test(tc1_1, writening_current_test);
  tcase_add_test(tc1_1, action_pause_test);
  tcase_add_test(tc1_1, move_test);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
